version: '3.8'
services:
  postgres:
    image: postgres:12
    container_name: postgres_backend
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: 
      context : .
      dockerfile : Dockerfile
    ports:
      - '3000:3000'
    command: bash -c "rm -f tmp/pids/server.pid && RAILS_ENV=test rspec"
    environment:
    #   DB_PASSWORD: mysecretpassword
    #   DB_NAME: audit_portal
        DB_USER: postgres
    #   DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
