version: '2.3'
services:
  database:
    image: postgres:12.4
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"

  app:

    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development

volumes:
  gem_cache:
  db_data:
  node_modules: