version: '2.3'
services:
  postgres:
    image: 'postgres:12.4'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - cybercert_postgres_data:/var/lib/postgresql/data/
volumes:
  cybercert_postgres_data: