name: Test

on:
  push:
    branches:
    - CI/CD
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker-compose -f "docker-compose.prod.yml" up -d --build

    - name: Run migrations
      run: docker-compose exec app rake db:setup db:migrate db:seed

    - name: Run Rspec Tests
      run: docker-compose exec app rspec

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.prod.yml" down